import { PublicContentPage, PublicUnavailable } from '@/components/public/PublicContentPage'
import { getPublicSiteProfile } from '@/lib/publicSite'
import { buildPublicMetadata } from '@/lib/seo'
export const metadata = buildPublicMetadata({ title: 'Garment Care Journal | Hangers Clothes Spa', description: 'Practical guidance for garment, curtain, stain, storage and footwear care from Hangers Clothes Spa.', path: '/blog' })

const guides=[
  ['Stains','What to do before a stain reaches the counter','Blot rather than rub, avoid heat, and tell the team what caused the stain. Home treatment can set some stains permanently.','The safest first step is often to stop and ask.'],
  ['Seasonal care','Putting woollens away properly','Clean before storing, dry fully, fold without compressing, and use a breathable storage cover away from damp walls.','Residue and moisture cause more storage damage than wear.'],
  ['Home textiles','When curtains need attention','Road-facing curtains collect fine dust faster. Vacuuming gently between professional cleans can reduce fibre wear at folds and leading edges.','Measure and inspect panels before removal.'],
  ['Bridal wear','Storing embellished garments','Heavy work needs breathable storage, supported folds and protection from humidity. Avoid direct contact with plastic for long periods.','Have stains and perspiration addressed before storage.'],
  ['Footwear','Drying shoes without causing damage','Direct sun can yellow some materials and distort adhesives. Use shade and airflow, and avoid aggressive brushing on delicate finishes.','Material determines the safe cleaning method.'],
  ['Care labels','Why the care label matters','The label helps identify fibre content and the manufacturer’s intended process, but construction and embellishment still need inspection.','Service decisions are made item by item.'],
]
export default async function BlogPage(){const profile=await getPublicSiteProfile();if(!profile)return <PublicUnavailable/>;const phone=profile.phone.replace(/\D/g,'');return <PublicContentPage profile={profile} eyebrow="Journal" title="Garment Care Journal" intro="Practical guidance from the Hangers counter: stains, storage, curtains, footwear and the small decisions that can prevent permanent damage.">
  <section className="dp-section"><article style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(340px,100%),1fr))',overflow:'hidden',border:'1px solid #dce8f0',borderRadius:16,background:'#fff'}}><img  src="/brand/curtain-care-hero.webp" alt="Professional curtain care at a customer home" width="1280" height="853" loading="lazy" style={{width:'100%',height:'100%',minHeight:320,objectFit:'cover'}}/><div style={{padding:'clamp(26px,3.4vw,40px)'}}><div className="dp-kicker">Curtain care</div><h2 className="dp-title">What to check before curtains come down</h2><p className="dp-copy" style={{marginBottom:14}}>Photograph the original fall, inspect weak stitching and note the lining. Fabric, sun exposure and prior shrinkage all affect the appropriate cleaning process.</p><p className="dp-copy">Hangers offers free curtain removal and reinstallation, with a typical turnaround of {profile.turnaround.curtains}.</p></div></article></section>
  <section className="dp-section"><div className="dp-grid">{guides.map(([category,title,body,takeaway])=><article className="dp-card" key={title} style={{display:'flex',flexDirection:'column',gap:13}}><div className="dp-kicker" style={{margin:0,color:'#023c62'}}>{category}</div><h2>{title}</h2><p style={{flex:1}}>{body}</p><div style={{paddingTop:13,borderTop:'1px dashed #dce8f0',color:'#7d93a8',fontSize:13.5,lineHeight:1.55}}>{takeaway}</div></article>)}</div></section>
  <section className="dp-band" style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:24,flexWrap:'wrap'}}><div><h2 className="dp-title">Have an item you are not sure about?</h2><p className="dp-copy">Send a clear photo of the fabric, label or stain before attempting a home treatment.</p></div><a className="dp-btn" href={`https://wa.me/${phone}`} target="_blank" rel="noreferrer">Ask Hangers on WhatsApp</a></section>
  </PublicContentPage>}
