import { PolicyPage, type PolicySection } from '@/components/public/PolicyPage'
import { buildPublicMetadata } from '@/lib/seo'

const title = 'Terms and Conditions'
const description = 'Terms for Hangers Clothes Spa dry-cleaning, ironing, curtain and home-care services in Mulund, Mumbai.'
export const metadata = buildPublicMetadata({ title: `${title} | Hangers Clothes Spa`, description, path: '/terms-and-conditions' })

const sections: PolicySection[] = [
  { title: 'Introduction', paragraphs: ['These terms and conditions ("terms") govern your use of the Hangers Clothes Spa website and your use of our dry-cleaning, ironing, curtain-care and other garment and home-care services. Hangers Clothes Spa is a local garment-care business serving Mulund West, Mumbai and nearby pickup areas. By browsing this website, submitting a pickup request, handing items to our team, or paying an invoice, you agree to these terms. Our operating address and current contact details are on the Contact Us page.'], link: { href: '/contact', label: 'View business address and contact details' } },
  { title: 'A pickup request is not yet a confirmed order', paragraphs: ['A website pickup form records your request and preferred time. Our team checks the address, service availability and schedule, then contacts you to confirm. The final service order and item list are established when the items are received and inspected. Please do not treat an unconfirmed request as a booked collection.'] },
  { title: 'Inspection, services and pricing', paragraphs: ['Hangers provides dry cleaning, laundry and ironing, curtain care, shoe care, sofa and upholstery care, and household textile care where available. The rate chart is a guide to the configured catalog. The condition, fabric, care label, construction, size and treatment required can affect whether an item is suitable and its final charge. We will discuss material changes to the requested service or price with you before proceeding. Typical turnaround times are estimates, not guaranteed completion appointments.'] },
  { title: 'Care outcomes and customer checks', paragraphs: ['Cleaning results depend on fabric, dyes, construction, prior treatment and the age or type of a stain. Stain removal cannot be guaranteed. Please empty pockets and tell us about delicate trims, existing damage, special care instructions or items of unusual value when handing items over. Check items at collection or delivery and tell us about a service concern within 24 hours so we can review the order while its details are available.'] },
  { title: 'Collection, delivery and payment', paragraphs: ['Pickup and delivery are local service arrangements in the areas shown on our website and are subject to confirmation. They are not parcel shipping. Payment is due as stated on your invoice or as otherwise agreed with Hangers. Online payments are processed by Razorpay; a payment is considered received only when the payment provider confirms success and Hangers records it against the correct invoice. Keep your invoice or payment reference if you contact us about a transaction.'] },
  { title: 'Cancellations, refunds and service concerns', paragraphs: ['Cancellation requests, billing adjustments and payment reversals are handled under the separate policy for these service orders.'], link: { href: '/cancellation-refund', label: 'Read the Cancellation and Refund Policy' } },
  { title: 'User responsibilities', paragraphs: ['When using this website or our services, you agree to provide accurate contact, address and pickup information; use the website only for lawful purposes and not to interfere with its operation or security; empty pockets and point out delicate trims, existing damage, special care needs or items of unusual value when handing items to our team; and check items at collection or delivery and raise a service concern within 24 hours as described above. You are responsible for keeping any account, OTP or payment confirmation you receive from us confidential and for the accuracy of information you submit through our forms.'] },
  { title: 'Intellectual property', paragraphs: ['The Hangers Clothes Spa name, logo, website design, text, images and other content on this website are owned by or licensed to Hangers Clothes Spa and are protected by applicable intellectual property laws. You may view and print pages of this website for your own personal, non-commercial use connected to your order. You may not copy, reproduce, republish, distribute or create derivative works from this website\'s content for any other purpose without our prior written consent.'] },
  { title: 'Limitation of liability', paragraphs: ['Hangers takes reasonable care in providing garment and home-care services, but cleaning and care outcomes depend on factors described above that are outside our control, including fabric, dyes, construction and prior treatment. To the extent permitted by law, our liability for a verified loss or damage to an item arising from our service is limited to the reasonable repair, re-service or replacement cost of that item, or the service charge paid for it, whichever is lower. We are not liable for indirect, incidental or consequential loss, including loss of use or sentimental value, except where such exclusion is not permitted by law. This website and its content are provided on an "as is" basis; we do not guarantee that the website will be uninterrupted or error-free. Nothing in these terms excludes or limits a liability or right that cannot lawfully be excluded or limited.'] },
  { title: 'Governing law', paragraphs: ['These terms are governed by the laws of India. Any dispute arising out of or relating to these terms or our services will be subject to the exclusive jurisdiction of the competent courts at Mumbai, Maharashtra.'] },
  { title: 'Changes to these terms', paragraphs: ['We may update service availability, prices, these terms or website content when our operations change. The version published here applies from its stated update date.'] },
]

export default function TermsPage() {
  return <PolicyPage title={title} intro="How Hangers accepts, inspects, prices and cares for garments and household items, and what to expect when you request a local pickup or pay an invoice." sections={sections} lastUpdated="1 October 2026" />
}
