import Link from 'next/link'
import { PublicContentPage, PublicUnavailable } from '@/components/public/PublicContentPage'
import { getPublicSiteProfile } from '@/lib/publicSite'
import { buildPublicMetadata } from '@/lib/seo'
export const metadata = buildPublicMetadata({ title: 'Contact Hangers Clothes Spa in Mulund West', description: 'Call, WhatsApp, email or visit Hangers Clothes Spa in Mulund West, Mumbai.', path: '/contact' })

export default async function ContactPage(){const p=await getPublicSiteProfile();if(!p)return <PublicUnavailable/>;const phone=p.phone.replace(/\D/g,'');const map=`https://www.google.com/maps?q=${encodeURIComponent(p.address)}&output=embed`;return <PublicContentPage profile={p} eyebrow="Contact" title="Visit or speak with the Hangers team." intro="Call, WhatsApp, email or visit the Mulund West shop. Photos of a fabric, label or stain are welcome when you need guidance before booking.">
  <section className="dp-split"><div style={{display:'grid',gap:26}}><div><div className="dp-kicker">Shop counter</div><div style={{fontSize:16.5,lineHeight:1.65}}>{p.address}</div></div><div><div className="dp-kicker">Hours</div><div style={{fontSize:16.5,lineHeight:1.75}}>{p.openingHours.map(x=><div key={x.label}>{x.label}: {x.hours}</div>)}</div></div><div><div className="dp-kicker">Reach us</div><div style={{fontSize:16.5,lineHeight:1.8}}><a href={`tel:${p.phone}`}>{p.phone}</a> · call<br/><a href={`https://wa.me/${phone}`} target="_blank" rel="noreferrer">WhatsApp Hangers</a><br/><a href={`mailto:${p.email}`}>{p.email}</a><br/><a href={p.instagramUrl} target="_blank" rel="noreferrer">Instagram @hangers.cs</a></div></div><div className="dw-actions"><Link className="dp-btn" href="/book-pickup">Book a pickup</Link><Link className="dp-btn secondary" href="/pickup-zones">Check your zone</Link></div></div><div><iframe className="dp-map" src={map} title="Map to Hangers Clothes Spa" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/><div className="dp-band" style={{marginTop:20}}><h2 style={{margin:'0 0 8px',color:'#023c62',fontSize:18}}>Google business profile</h2><p className="dp-copy" style={{fontSize:14.5,marginBottom:14}}>{p.googleRating} stars from {p.googleReviewCount} Google reviews.</p><a className="dp-btn secondary" href={p.mapUrl} target="_blank" rel="noreferrer">Open directions</a></div></div></section>
  </PublicContentPage>}
