import Link from 'next/link'
import { PublicContentPage, PublicUnavailable } from '@/components/public/PublicContentPage'
import { getPublicSiteProfile } from '@/lib/publicSite'
import { buildPublicMetadata } from '@/lib/seo'
export const metadata = buildPublicMetadata({ title: 'About Hangers Clothes Spa | Serving Mulund Since 2018', description: 'Learn about Hangers Clothes Spa, serving Mulund West with tracked garment and curtain care since 2018.', path: '/about' })

export default async function AboutPage(){const profile=await getPublicSiteProfile();if(!profile)return <PublicUnavailable/>;return <PublicContentPage profile={profile} eyebrow="About" title="A neighbourhood garment-care shop built around clear service." intro={`${profile.businessName} has served Mulund West since ${profile.establishedYear}. We combine hands-on item inspection with barcode tracking, live pricing and WhatsApp order updates.`}>
  <section className="dp-section dp-split"><img className="dp-media" src="/brand/garment-care-hero.webp" alt="Hangers garment-care professional inspecting a shirt" width="1280" height="607" loading="lazy"/><div><p className="dp-copy" style={{fontSize:16.5,marginBottom:16}}>Hangers Clothes Spa works with garments, ironing, curtains, footwear and household furnishings from its Mulund West shop.</p><p className="dp-copy" style={{fontSize:16.5,marginBottom:16}}>The service begins with the item itself: its fabric, construction, care label and condition. The right process and expected timing are confirmed before the order proceeds.</p><p className="dp-copy" style={{fontSize:16.5}}>Technology supports that work rather than replacing it. Barcode tracking and WhatsApp status updates help customers follow regular orders clearly.</p></div></section>
  <section className="dp-section"><div className="dp-facts"><div className="dp-fact"><strong>{profile.establishedYear}</strong><span>Serving the neighbourhood since</span></div><div className="dp-fact"><strong>{profile.googleRating} / 5</strong><span>Google rating from {profile.googleReviewCount} reviews</span></div><div className="dp-fact"><strong>{profile.pickupZones.length}</strong><span>Primary pickup areas</span></div><div className="dp-fact"><strong>{profile.turnaround.dryCleaning}</strong><span>Typical dry-cleaning turnaround</span></div></div></section>
  <section className="dp-section" style={{padding:'58px 0',borderTop:'1px solid #dce8f0',borderBottom:'1px solid #dce8f0'}}><h2 className="dp-title">The Hangers approach, briefly</h2><div className="dp-grid"><div style={{borderTop:'2px solid #023c62',paddingTop:16}}><strong style={{color:'#023c62'}}>Inspect</strong><p className="dp-copy" style={{fontSize:14.5,marginTop:8}}>Review the item, service requirement and visible concerns at intake.</p></div><div style={{borderTop:'2px solid #023c62',paddingTop:16}}><strong style={{color:'#023c62'}}>Track</strong><p className="dp-copy" style={{fontSize:14.5,marginTop:8}}>Use order and barcode records to keep garments linked to the correct customer.</p></div><div style={{borderTop:'2px solid #023c62',paddingTop:16}}><strong style={{color:'#023c62'}}>Update</strong><p className="dp-copy" style={{fontSize:14.5,marginTop:8}}>Send relevant WhatsApp status messages as regular orders progress.</p></div></div></section>
  <section className="dp-section dp-split" style={{paddingTop:56}}><div><h2 className="dp-title">Curtain care at home</h2><p className="dp-copy">Curtain cleaning includes free removal and reinstallation. Typical curtain turnaround is {profile.turnaround.curtains}, subject to fabric and site access.</p></div><div className="dp-band"><h2 style={{margin:'0 0 12px',color:'#023c62',fontSize:20}}>Where to find us</h2><p className="dp-copy" style={{marginBottom:18}}>{profile.address}</p><Link className="dp-btn secondary" href="/contact">Contact and directions</Link></div></section>
  </PublicContentPage>}
