export const crmRoutes = [
  '/dashboard',
  '/dashboard/orders',
  '/dashboard/orders?view=in_process',
  '/dashboard/orders?view=ready',
  '/dashboard/orders?view=delivered',
  '/dashboard/orders/new',
  '/dashboard/iron/sheet',
  '/dashboard/iron/logs',
  '/dashboard/iron/applications',
  '/dashboard/iron/monthly',
  '/dashboard/pickup-requests',
  '/dashboard/quotations',
  '/dashboard/service-appointments',
  '/dashboard/plantchallans',
  '/dashboard/print',
  '/dashboard/recurring',
  '/dashboard/customers',
  '/dashboard/referrals',
  '/dashboard/promotions',
  '/dashboard/marketing',
  '/dashboard/pricing',
  '/dashboard/finance',
  '/dashboard/cashbook',
  '/dashboard/expenses',
  '/dashboard/staff',
  '/dashboard/attendance',
  '/dashboard/reports',
  '/dashboard/logs',
  '/dashboard/search',
  '/dashboard/ar-challans',
] as const

export const auditDevices = [
  { name: 'phone-320', width: 320, height: 568 },
  { name: 'phone-390', width: 390, height: 844 },
  { name: 'tablet-768', width: 768, height: 1024 },
  { name: 'tablet-landscape', width: 1024, height: 768 },
  { name: 'desktop-1440', width: 1440, height: 900 },
] as const
