import { PolicyPage, type PolicySection } from '@/components/public/PolicyPage'
import { buildPublicMetadata } from '@/lib/seo'

const title = 'Privacy Policy'
const description = 'How Hangers Clothes Spa handles information submitted for local garment-care services, pickup requests and payments.'
export const metadata = buildPublicMetadata({ title: `${title} | Hangers Clothes Spa`, description, path: '/privacy-policy' })

const sections: PolicySection[] = [
  { title: 'Our approach', paragraphs: ['Hangers Clothes Spa uses information entrusted to us to arrange and perform garment-care services, communicate about orders and payments, and operate this website. This notice describes the information used in those activities and the choices available to you. Razorpay processes online payment details under its own terms and privacy notice.'] },
  { title: 'Information you provide', paragraphs: ['When you contact us, request a pickup, or place an order, we may receive your name, mobile number, email address, pickup or delivery address, requested services, preferred collection time, item and care details, order history, messages and support queries. We use payment references and transaction status to match a payment to an invoice; online payment credentials are entered into Razorpay’s checkout, not requested in our pickup form.'] },
  { title: 'How we use it', paragraphs: [], bullets: ['Confirm service-area coverage and contact you about pickup scheduling.', 'Identify items and orders, record inspection and service progress, and arrange return delivery.', 'Issue invoices and receipts, reconcile payments, and investigate payment or service questions.', 'Send relevant service and order updates through the contact channel used for your order.', 'Protect the website and our records, prevent misuse, maintain operational accounts, and meet applicable record-keeping obligations.', 'Understand public website usage and improve pages using Google Analytics and Google Tag Manager.'] },
  { title: 'When information is shared', paragraphs: ['We share only information needed for the relevant task with service providers that support our operations. These may include Razorpay for payment processing, website and cloud hosting providers, and communication providers used to send customer updates. A provider may process information under its own privacy terms. We do not publish customer order details as public website content. We may also disclose records where required by law or to investigate fraud, security incidents or a customer dispute.'] },
  { title: 'Website measurement and device information', paragraphs: ['The public website loads Google Analytics and Google Tag Manager on its marketing domain. Those services may receive technical and page-usage information such as pages viewed, browser/device signals and approximate network-derived information according to Google’s settings and policies. Your browser also stores limited session data when you use features such as pickup verification. You can use browser controls to limit cookies or storage; some site functions may then not work as intended.'] },
  { title: 'Retention and security', paragraphs: ['We keep order, service, payment and customer-contact records for as long as they are needed to provide services, answer questions, reconcile accounts, address disputes, meet legal/accounting duties, and protect the business. Retention can therefore depend on the record and the reason it was created. We use access controls and operational safeguards, but no internet transmission or storage method can be promised to be completely risk-free.'] },
  { title: 'Your requests and contact', paragraphs: ['You may contact us to ask what customer information relates to your order, correct inaccurate contact details, or raise a privacy concern. We may need to verify that you are the customer before changing or disclosing an order record. Some transaction records may need to be retained for accounting, legal or dispute-resolution purposes.'] },
  { title: 'Updates to this notice', paragraphs: ['We may revise this notice when our website, service providers or practices change. The update date at the top of the page indicates the current published version.'] },
]

export default function PrivacyPage() {
  return <PolicyPage title={title} intro="A plain-language explanation of the customer and order information Hangers uses to provide dry cleaning, local pickup and delivery, payment reconciliation and support." sections={sections} />
}
