-- AlterTable
ALTER TABLE "OrderItem"
ADD COLUMN "baseUnitPrice" DOUBLE PRECISION,
ADD COLUMN "lineDiscountType" TEXT,
ADD COLUMN "lineDiscountValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "lineDiscountAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
